# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\base_ui\mtdInputDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(409, 252)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 5, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.freqListText = QtWidgets.QTextBrowser(self.groupBox)
        self.freqListText.setObjectName("freqListText")
        self.gridLayout_4.addWidget(self.freqListText, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 3, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.NT_label = QtWidgets.QLabel(self.groupBox_2)
        self.NT_label.setObjectName("NT_label")
        self.gridLayout_2.addWidget(self.NT_label, 0, 0, 1, 1)
        self.NT_lineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.NT_lineEdit.setObjectName("NT_lineEdit")
        self.gridLayout_2.addWidget(self.NT_lineEdit, 0, 1, 1, 1)
        self.T_label = QtWidgets.QLabel(self.groupBox_2)
        self.T_label.setObjectName("T_label")
        self.gridLayout_2.addWidget(self.T_label, 1, 0, 1, 1)
        self.T_lineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.T_lineEdit.setObjectName("T_lineEdit")
        self.gridLayout_2.addWidget(self.T_lineEdit, 1, 1, 1, 1)
        self.Q_label = QtWidgets.QLabel(self.groupBox_2)
        self.Q_label.setObjectName("Q_label")
        self.gridLayout_2.addWidget(self.Q_label, 2, 0, 1, 1)
        self.Q_lineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.Q_lineEdit.setObjectName("Q_lineEdit")
        self.gridLayout_2.addWidget(self.Q_lineEdit, 2, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox_2, 1, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.freqFileName = QtWidgets.QLineEdit(self.groupBox_3)
        self.freqFileName.setObjectName("freqFileName")
        self.gridLayout_3.addWidget(self.freqFileName, 1, 0, 1, 1)
        self.freqFileButton = QtWidgets.QToolButton(self.groupBox_3)
        self.freqFileButton.setObjectName("freqFileButton")
        self.gridLayout_3.addWidget(self.freqFileButton, 1, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox_3, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Импорт частот"))
        self.groupBox_2.setTitle(_translate("Dialog", "Дополнительные параметры"))
        self.NT_label.setText(_translate("Dialog", "NT"))
        self.T_label.setText(_translate("Dialog", "T"))
        self.Q_label.setText(_translate("Dialog", "Q"))
        self.groupBox_3.setTitle(_translate("Dialog", "Импорт"))
        self.freqFileButton.setText(_translate("Dialog", "Частоты"))
