# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\SimpleModelDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(361, 496)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox_3 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.modelFileName = QtWidgets.QLineEdit(self.groupBox_3)
        self.modelFileName.setObjectName("modelFileName")
        self.gridLayout_3.addWidget(self.modelFileName, 0, 0, 1, 1)
        self.modelFileButton = QtWidgets.QToolButton(self.groupBox_3)
        self.modelFileButton.setObjectName("modelFileButton")
        self.gridLayout_3.addWidget(self.modelFileButton, 0, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_3)
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.modelTableWidget = QtWidgets.QTableWidget(self.groupBox)
        self.modelTableWidget.setAlternatingRowColors(False)
        self.modelTableWidget.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.modelTableWidget.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.modelTableWidget.setRowCount(8)
        self.modelTableWidget.setObjectName("modelTableWidget")
        self.modelTableWidget.setColumnCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.modelTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.modelTableWidget.setHorizontalHeaderItem(1, item)
        self.modelTableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.modelTableWidget.horizontalHeader().setHighlightSections(True)
        self.modelTableWidget.horizontalHeader().setStretchLastSection(True)
        self.gridLayout.addWidget(self.modelTableWidget, 0, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.deleteRowButton = QtWidgets.QToolButton(Dialog)
        self.deleteRowButton.setObjectName("deleteRowButton")
        self.horizontalLayout_2.addWidget(self.deleteRowButton)
        self.addRowButton = QtWidgets.QToolButton(Dialog)
        self.addRowButton.setObjectName("addRowButton")
        self.horizontalLayout_2.addWidget(self.addRowButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Создание модели"))
        self.groupBox_3.setTitle(_translate("Dialog", "Импорт"))
        self.modelFileButton.setText(_translate("Dialog", "Модель"))
        self.groupBox.setTitle(_translate("Dialog", "Модель"))
        item = self.modelTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Ro"))
        item = self.modelTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "H"))
        self.deleteRowButton.setText(_translate("Dialog", "--"))
        self.addRowButton.setText(_translate("Dialog", "+"))
